# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"A": "00_core.ipynb",
         "B": "00_core.ipynb",
         "DEFAULT_EXPORT_WORKS": "01_different_module.ipynb"}

modules = ["core.py",
           "different_module.py"]

doc_url = "https://fastai.github.io/nbdev_template/"

git_url = "https://github.com/fastai/nbdev_template/tree/master/"

def custom_doc_links(name): return None
