# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['A']

# Cell

class A:
    """The Class A."""
    def __init__(self, value):
        self.value = value