# AUTOGENERATED! DO NOT EDIT! File to edit: 01_different_module.ipynb (unless otherwise specified).

__all__ = ['DEFAULT_EXPORT_WORKS', 'B']

# Cell

DEFAULT_EXPORT_WORKS=1

# Comes from 02_core.ipynb, cell

class B:
    """The Class A."""
    def __init__(self, value):
        self.value = value